spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phone_shop
    username: postgres
    password: roth9999
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false